Add missing includes for iovec
src/output/StreamThreadHttp.cpp:77:8: error: variable has incomplete type 'iovec'
src/output/StreamThreadRtpTcp.cpp:96:8: error: variable has incomplete type 'iovec'