Add missing include for socket handling
src/output/StreamThreadRtcp.cpp:54:30: error: use of undeclared identifier 'SOCK_DGRAM'
src/output/StreamThreadRtp.cpp:56:29: error: use of undeclared identifier 'SOCK_DGRAM'
src/socket/SocketAttr.cpp:57:27: error: use of undeclared identifier 'AF_INET'